# Sample workflow to access AWS resources when workflow is tied to branch
# The workflow Creates static website using aws s3
name: AWS example workflow

on:
  push:
    branches:
      - ab/deploy-pgstac
  # enable a workflow to be triggered manually
  workflow_dispatch:
    inputs:
      deployment_environment:
        description: 'environment'
        required: true

env:
  BUCKET_NAME : "nasa-eodc-data-store"
  AWS_REGION : "us-west-2"
# permission can be added at job level or workflow level    
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
jobs:
  S3PackageUpload:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::444055461661:role/github-actions-role-eodc
          role-session-name: samplerolesession
          aws-region: ${{ env.AWS_REGION }}
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 18
    - name: Install deployment dependencies
      run: npm install
    - name: Run CDK deploy
      run: |
        npm install -g aws-cdk
        cdk deploy --all --require-approval never --region us-west-2