name: Deploy pgSTAC to AWS

on:
  push:
    branches:
      - main
  # enable a workflow to be triggered manually
  workflow_dispatch:
    inputs:
      deployment_environment:
        description: 'environment'
        required: true

env:
  AWS_REGION : "us-west-2"
# permission can be added at job level or workflow level    
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout
jobs:
  check_commit:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
    steps:
    - name: Git clone the repository
      uses: actions/checkout@v3    
    - name: Check commit message
      id: check
      run: |
        message=$(git log --format=%B -n 1 ${{ github.event.after }})
        if [[ "$message" == *"deploy"* ]]; then
          echo "::set-output name=should_run::true"
        else
          echo "::set-output name=should_run::false"
        fi

  deploy-pgstac:
    needs: check_commit
    if: needs.check_commit.outputs.should_run == 'true' 
    runs-on: ubuntu-latest
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::444055461661:role/github-actions-role-eodc
          role-session-name: samplerolesession
          aws-region: ${{ env.AWS_REGION }}
      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install deployment dependencies
        run: npm install
      - name: Run CDK deploy
        run: |
          npm install -g aws-cdk
          cdk deploy --all --require-approval never --region us-west-2
